# Generated by Django 6.0.7 on 2026-08-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herobanner',
            old_name='button_link',
            new_name='primary_button_link',
        ),
        migrations.RenameField(
            model_name='herobanner',
            old_name='button_text',
            new_name='primary_button_text',
        ),
        migrations.AddField(
            model_name='herobanner',
            name='badge',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='hero_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='secondary_button_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='secondary_button_text',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='herobanner',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
